// <auto-generated />
using System;
using Ironbell.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ironbell.Infrastructure.Migrations
{
    [DbContext(typeof(IronbellDbContext))]
    partial class IronbellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ironbell.Domain.AppInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalised")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name_normalised");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("schema_version");

                    b.Property<DateTime>("SeededAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("seeded_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_app_info");

                    b.HasIndex("NameNormalised")
                        .IsUnique()
                        .HasDatabaseName("ix_app_info_name_normalised");

                    b.ToTable("app_info", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyToken = 0,
                            Name = "Ironbell",
                            NameNormalised = "ironbell",
                            SchemaVersion = "m0",
                            SeededAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
