#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Draws the Ironbell app icons from the design tokens.

.DESCRIPTION
    A placeholder mark, but a deliberate one: dark iron ground, a kettlebell silhouette, and the
    16 kg competition yellow as the accent. Better than shipping the Blazor template's logo to a
    home screen, and honest about being provisional.

    Generated by script rather than committed as hand-made binaries so the mark can be regenerated
    when the real asset arrives, and so the colours cannot drift from app.css by hand-editing.

    Windows only: System.Drawing.Common is a Windows-only surface on modern .NET. Icons change
    rarely and the outputs are committed, so CI never runs this.

.EXAMPLE
    ./scripts/build-icons.ps1
#>
[CmdletBinding()]
param(
    [string] $OutputDirectory = 'src/Ironbell.Client/wwwroot'
)

$ErrorActionPreference = 'Stop'

if (-not $IsWindows) { throw 'This script needs System.Drawing.Common, which is Windows-only.' }

Add-Type -AssemblyName System.Drawing

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$target = Join-Path $repositoryRoot $OutputDirectory

# Must match the tokens in wwwroot/css/app.css.
$ironBase = [System.Drawing.ColorTranslator]::FromHtml('#17171A')
$ironLight = [System.Drawing.ColorTranslator]::FromHtml('#F2F2F4')
$bell16 = [System.Drawing.ColorTranslator]::FromHtml('#F2C400')

function New-IronbellIcon {
    param([int] $Size, [string] $Path)

    $bitmap = New-Object System.Drawing.Bitmap($Size, $Size)
    $g = [System.Drawing.Graphics]::FromImage($bitmap)
    try {
        $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
        $g.Clear($ironBase)

        $u = $Size / 100.0   # work in percentage units so every size is identical in proportion

        # Handle: an open arc, drawn as a thick stroke.
        $handlePen = New-Object System.Drawing.Pen($ironLight, [float](9 * $u))
        $handlePen.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
        $handlePen.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
        # The arc is drawn narrower than the bell and ends below the bell's top edge, so the legs
        # meet the mass instead of appearing to float above it.
        $g.DrawArc($handlePen, [float](35 * $u), [float](20 * $u), [float](30 * $u), [float](38 * $u), 180, 180)
        $handlePen.Dispose()

        # Bell: the mass, in iron light. Drawn after the handle so it covers the leg ends.
        $bellBrush = New-Object System.Drawing.SolidBrush($ironLight)
        $g.FillEllipse($bellBrush, [float](22 * $u), [float](38 * $u), [float](56 * $u), [float](48 * $u))
        $bellBrush.Dispose()

        # Weight band: the competition colour, functional rather than decorative.
        $bandBrush = New-Object System.Drawing.SolidBrush($bell16)
        $g.FillRectangle($bandBrush, [float](34 * $u), [float](72 * $u), [float](32 * $u), [float](7 * $u))
        $bandBrush.Dispose()

        $bitmap.Save((Join-Path $target $Path), [System.Drawing.Imaging.ImageFormat]::Png)
        Write-Host ("{0}  {1}x{1}" -f $Path, $Size)
    }
    finally {
        $g.Dispose()
        $bitmap.Dispose()
    }
}

New-IronbellIcon -Size 512 -Path 'icon-512.png'
New-IronbellIcon -Size 192 -Path 'icon-192.png'
New-IronbellIcon -Size 64 -Path 'favicon.png'

Write-Host "Icons written to $target."
